name: Container Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ghcr.io/pwr-pro/pystebin:latest -f Containerfile .
      

      - uses: anchore/scan-action@v3
        id: scan
        with:
          image: "ghcr.io/pwr-pro/pystebin:latest"
          fail-build: true
          severity-cutoff: critical

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_KEY }}
      
      - name: Push Docker image
        run: docker push ghcr.io/pwr-pro/pystebin:latest
      
