name: Container Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Container image
        run: docker build . --file Containerfile --tag ghcr.io/pwr-pro/pystebin:latest
      - uses: anchore/scan-action@v3
        id: scan
        with:
          image: "ghcr.io/pwr-pro/pystebin:latest"
      - name: upload Anchore scan SARIF report
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
